repos:
-   repo: local
    hooks:
    - id: fmt
      name: fmt
      description: format
      entry: cargo fmt
      language: system
      types: ["rust"]
      stages: ["commit"]
      pass_filenames: false
    - id: test
      name: test
      description: run tests
      entry: cargo test
      language: system
      types: ["rust"]
      stages: ["push"]
      pass_filenames: false
    - id: trace
      name: trace
      description: verify that all requirements are traced correctly
      entry: cargo run check
      language: system
      types: ["file"]
      stages: ["manual"] # TODO: "push",
      pass_filenames: false
    - id: tmx
      name: tmx
      description: build traceability matrix
      entry: cargo run tmx
      language: system
      types: ["file"]
      stages: ["push", "manual"]
      pass_filenames: false
