[package]
name = "reqtrace"
version = "0.1.0"
authors = ["Wonko <wonko@hanstool.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4"
lazy_static = "1.4"
once_cell = "1.7"
