default_jobs = ["check"]

[[artefacts]]
id = "readme"
paths = ["README.md", ]
parser = "Readme"
ignore_derived_requirements = true

[[artefacts]]
id = "requirements"
paths = ["doc/requirements/REQUIREMENTS.md", ]
parser = "Markdown"
ignore_derived_requirements = true

[[artefacts]]
id = "architecture"
paths   = ["doc/requirements/ARCHITECTURE.md", ]
parser  = "Markdown"

[[artefacts]]
id = "design"
paths   = ["doc/requirements/DESIGN.md", ]
parser  = "Markdown"

[[artefacts]]
id = "formats"
paths =  ["doc/requirements/FORMATS.md", ]
parser = "Markdown"

[[artefacts]]
id = "code"
paths = ["src/**/*.rs"]
parser = "Rust"

[[relations]]
upper = "readme"
lower = ["requirements", ]

[[relations]]
upper = "requirements"
lower = ["design", "formats", "architecture" ]

[[relations]]
upper = "architecture"
lower = ["design", ]

[[relations]]
upper="design"
lower= ["formats", "code", ]

[[relations]]
upper="formats"
lower= ["code", ]

[jobs.tags]
query = "Parse"
format = "Tags"
file = ".tags"
set_return_code = false

[jobs.tmx]
query = "Trace"
format = "Markdown"
file = "reports/tmx.md"
set_return_code = false

[jobs.export]
query = "Trace"
format = "Json"
file = "reports/tmx.json"
set_return_code = false

[jobs.check]
query = "Trace"
format = "GnuError"
file = "-"
