version_provider = "git"
default_jobs = ["errors"]

[artefact.requirements]
paths = ["doc/requirements/REQUIREMENTS.md", ]
parser = "markdown"

[artefact.design]
paths   = ["doc/requirements/DESIGN.md", ]
parser  = "markdown"

[artefact.formats]
paths =  ["doc/requirements/FORMATS.md", ]
parser = "markdown"

[artefact.code]
paths = ["src/**/*.rs"]
parser = "rust_cov_mark"

[[trace]]
upper = "requirements"
lower = ["design", "formats", ]

[[trace]]
upper="design"
lower= ["formats", "code", ]

[[trace]]
upper="formats"
lower= ["code", ]

[job.tags]
query = "Parse"
format = "Tags"
file = ".tags"

[job.tmx]
query = "Trace"
format = "Markdown"
file = "reports/tmx.md"


[job.errors]
query = "Trace"
format = "GnuError"
file = "-"

