version_provider = "git"

[artefact.requirements]
paths = ["doc/requirements/REQUIREMENTS.md", ]
parser = "markdown"

[artefact.design]
paths   = ["doc/requirements/DESIGN.md", ]
parser  = "markdown"

[artefact.formats]
paths =  ["doc/requirements/FORMATS.md", ]
parser = "markdown"

[artefact.code]
paths = ["src/**/*.rs"]
parser = "rust_cov_marks"

[artefact.unsafe_code]
paths =  ["src/**/*.rs"]
parser = "rust_unsafe"

[artefact.unsafe_reasoning]
paths = ["doc/requirements/unsafe_reasoning.md"]
parser = "markdown"

[[trace]]
upper = "requirements"
lower = ["design", "formats", ]

[[trace]]
upper="design"
lower= ["formats", "code", ]

[[trace]]
upper="formats"
lower= ["code", ]

[[trace]]
upper="unsafe_code"
lower= ["unsafe_reasoning", ]

[job.tags]
query = "Parse"
format = "Tags"
file = ".tags"

[job.tmx]
query = "Trace"
format = "Markdown"
file = "reports/tmx.md"


