version_provider = "git"
default_jobs = ["check"]


[artefact.readme]
paths = ["README.md", ]
parser = "readme"

[artefact.requirements]
paths = ["doc/requirements/REQUIREMENTS.md", ]
parser = "markdown"

[artefact.design]
paths   = ["doc/requirements/DESIGN.md", ]
parser  = "markdown"

[artefact.formats]
paths =  ["doc/requirements/FORMATS.md", ]
parser = "markdown"

[artefact.code]
paths = ["src/**/*.rs"]
parser = "rust"

[[trace]]
upper = "readme"
lower = ["requirements", ]

[[trace]]
upper = "requirements"
lower = ["design", "formats", ]

[[trace]]
upper="design"
lower= ["formats", "code", ]

[[trace]]
upper="formats"
lower= ["code", ]

[job.tags]
query = "Parse"
format = "Tags"
file = ".tags"
set_return_code = false

[job.build]
query = "Trace"
format = "Markdown"
file = "reports/tmx.md"
set_return_code = false

[job.check]
query = "Trace"
format = "GnuError"
file = "-"
